language: node_js
node_js:
  - '4.2'
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
script:
  - './node_modules/gulp/bin/gulp.js build'
  - './node_modules/.bin/karma start --browsers Firefox --single-run'